#!/usr/bin/env bash
#Bash script that installs HAProxy & makes configurations

# Install HAProxy
sudo apt update
sudo apt install -y haproxy

# Configure HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http-in
    bind *:80
    default_backend webservers

backend webservers
    balance roundrobin
    server web-01  606229561-web-01:80 check
    server web-02  606229561-web-02:80 check
EOF

# Enable HAProxy as a service and start it
sudo systemctl enable haproxy
sudo systemctl start haproxy
