#!/usr/bin/env bash

# Update the package index and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Configure Nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default

# Create a custom HTML page with the string "Holberton School"
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html > /dev/null

# Restart Nginx to apply the changes
sudo service nginx restart

